name: aws-devops-ci

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'src/base/Dockerfile'
      - 'action.yml'
      - 'src/shell/**.sh'
      - 'src/templates/**.tmpl'

  release:
    types: [published]
  
jobs:

  build_push_image:
    name: Build and Push Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: wilton/awscli-devops-ci:${{ steps.tag_version.outputs.new_tag }}
          context: src/base/Dockerfile

      - name: Show Tag image
        run: |
          echo "wilton/awscli-devops-ci:${{ steps.tag_version.outputs.new_tag }}"